### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Surfdaweb** [Surfdaweb/momitare#14]
### Acceptance Criteria

- [x]  The main call-to-action is to start a new game (clicking that CTA doesn't need to do anything for the sake of this story)
- [x]  The name of the site (Momitare) is visible and prominent
- [ ]  A general site design language is defined - preferably something recognizable and traditional to card games

**Comment by Surfdaweb** [comment]
https://www.realtimecolors.com/?colors=ddeede-142415-ffffff-000000-901513&fonts=Tauri-Tauri

This site represents the colors & fonts that I wanna use for the general look and feel of the site. We'll stick to a simple, flat design for the sake of simplicity, and we'll put our fancy designer energy into those cards!

**Comment by Surfdaweb** [comment]
The CSS for the card table background:

```css
html {
  --s: 10px; /* control the size */
  --c1: #122113;
  --c2: #1b311d;
  
  --g: var(--c1)    3.125%,var(--c2) 0 9.375%,
       var(--c1) 0 15.625%,var(--c2) 0 21.875%,
       var(--c1) 0 28.125%,#0000 0;
  background: 
    linear-gradient(225deg,#0000    3.125%,var(--c2) 0 9.375%,
                           #0000 0 78.125%,var(--c2) 0 84.375%,#0000 0) 
     0 calc(var(--s)/2),
    linear-gradient( 45deg,var(--g)) 0 var(--s),
    linear-gradient( 45deg,var(--g)) calc(var(--s)/-2) calc(var(--s)/-2),
    linear-gradient(225deg,var(--g)) var(--s) 0,
    linear-gradient(225deg,var(--g)) calc(var(--s)/2) var(--s),
    repeating-linear-gradient(-45deg,var(--c1) -3.125% 3.125%,var(--c2) 0 9.375%);
  background-size: calc(2*var(--s)) calc(2*var(--s));
}*/
```

**Comment by Surfdaweb** [comment]
CSS idea for the card back:

```css
html {
  --s: 220px; /* control the size */
  --c1: #ea6361;
  --c2: #871412;

  --_g: 
     var(--c1) 0%  5% ,var(--c2) 6%  15%,var(--c1) 16% 25%,var(--c2) 26% 35%,var(--c1) 36% 45%,
     var(--c2) 46% 55%,var(--c1) 56% 65%,var(--c2) 66% 75%,var(--c1) 76% 85%,var(--c2) 86% 95%,
     #0000 96%;
  background:
    radial-gradient(50% 50% at 100% 0,var(--_g)),
    radial-gradient(50% 50% at 0 100%,var(--_g)),
    radial-gradient(50% 50%,var(--_g)),
    radial-gradient(50% 50%,var(--_g)) calc(var(--s)/2) calc(var(--s)/2)
    var(--c1);
  background-size: var(--s) var(--s);
}

```
